### ISSUE TITLE
Missing of modules “src.data“ 

### ISSUE THREAD

**Issue by YifaSuoha962** [igashov/RetroBridge#1]
Thank you for your excellent work! 
When running the training codes, I found modules corresponding to `from src.data.retrobridge_dataset import RetroBridgeDatasetInfos, RetroBridgeDataset` are missed, could you offer the missing modules?

**Comment by igashov** [comment]
Sorry, added these directories to `.gitignore` by mistake. Now all modules are uploaded. Thank you!
