### ISSUE TITLE
parameter recommendations

### ISSUE THREAD

**Issue by anjie-qiao** [igashov/RetroBridge#3]
Dear Author,
I am very interested in your work!
I am trying to replicate the results mentioned in this paper. Could you please confirm if the parameters provided in the [retrobridge.yaml] are the recommended ones for achieving the best results? Alternatively, do you have any other suggestions for parameter settings? 
Thank you very much for your assistance!

**Comment by joneswong** [comment]
+1
I am also attempting to reproduce the reported results. Could you kindly share the optimal hyper-parameters with the community so that we could better follow your great work! Thanks!

**Comment by arneschneuing** [comment]
Hi @anjie-qiao and @joneswong, the parameters in this config file should be correct: https://github.com/igashov/RetroBridge/blob/main/configs/retrobridge.yaml
Best, Arne

**Comment by anjie-qiao** [comment]
Thanks for your reply! I will try to hack the issue with your advice.  Many thanks again!
